// HOAI 2021 fee table § 21 and work-stage (LPH) percentages of § 19
// — bebauungsplan (decision E-13, plan 79-14).
//
// In:  nothing (import-free, like tafel2021.js). Out: TAFEL, a frozen HoaiTafel
//      record (typedef in ../leistungsbilder.js).
//
// Source: https://www.gesetze-im-internet.de/hoai_2013/__21.html (fetched 2026-09-28). Generated by
// .planning/phases/79-buchhaltung/tmp-e2e/hoai-tafeln-abruf.mjs — do not edit
// by hand; re-run the script on a new legal version and add a NEW file with a
// new `ab` date instead of overwriting this one.
//
// Deviation from the objective's expectation (79-RESEARCH.md), fetched text wins:
// - bebauungsplan: Honorartafel hat 1 Plateau-Stelle(n) (gleicher Wert zweier Zeilen) — echter amtlicher Text (Mindesthonorar für die kleinsten Flächen), keine Extrapolationslücke.

/** Deep freeze for plain data (objects and arrays). @template T @param {T} wert @returns {T} */
function friere(wert) {
  if (wert && typeof wert === "object" && !Object.isFrozen(wert)) {
    for (const k of Object.keys(wert)) friere(/** @type {any} */ (wert)[k]);
    Object.freeze(wert);
  }
  return wert;
}

/** @type {import("../leistungsbilder.js").HoaiTafel} */
export const TAFEL = friere({
  leistungsbild: "bebauungsplan",
  paragraf: 21,
  fassung: "HOAI 2021",
  bezug: "flaeche_ha",
  einheit: "ha",
  zonen: ["I","II","III"],
  zeilen: [
  [0.5, [5000, 5335, 7838, 10341]],
  [1, [5000, 8799, 12926, 17054]],
  [2, [7699, 14502, 21305, 28109]],
  [3, [10306, 19413, 28521, 37628]],
  [4, [12669, 23866, 35062, 46258]],
  [5, [14864, 28000, 41135, 54271]],
  [6, [16931, 31893, 46856, 61818]],
  [7, [18896, 35595, 52294, 68992]],
  [8, [20776, 39137, 57497, 75857]],
  [9, [22584, 42542, 62501, 82459]],
  [10, [24330, 45830, 67331, 88831]],
  [15, [32325, 60892, 89458, 118025]],
  [20, [39427, 74270, 109113, 143956]],
  [25, [46385, 87376, 128366, 169357]],
  [30, [52975, 99791, 146606, 193422]],
  [40, [65342, 123086, 180830, 238574]],
  [50, [76901, 144860, 212819, 280778]],
  [60, [87599, 165012, 242425, 319838]],
  [80, [107471, 202445, 297419, 392393]],
  [100, [125791, 236955, 348119, 459282]],
  ],
  lph: [
  { nr: 1, bezeichnung: "Vorentwurf für die frühzeitigen Beteiligungen", prozent: 60 },
  { nr: 2, bezeichnung: "Entwurf zur öffentlichen Auslegung", prozent: 30 },
  { nr: 3, bezeichnung: "Plan zur Beschlussfassung", prozent: 10 },
  ],
  lphParagraf: 19,
  umbau_max_prozent: null,
  quelle: "https://www.gesetze-im-internet.de/hoai_2013/__21.html",
  abgerufen_am: "2026-09-28",
  status: "amtlich",
});
