// HOAI 2021 fee table § 20 and work-stage (LPH) percentages of § 18
// — flaechennutzungsplan (decision E-13, plan 79-14).
//
// In:  nothing (import-free, like tafel2021.js). Out: TAFEL, a frozen HoaiTafel
//      record (typedef in ../leistungsbilder.js).
//
// Source: https://www.gesetze-im-internet.de/hoai_2013/__20.html (fetched 2026-09-28). Generated by
// .planning/phases/79-buchhaltung/tmp-e2e/hoai-tafeln-abruf.mjs — do not edit
// by hand; re-run the script on a new legal version and add a NEW file with a
// new `ab` date instead of overwriting this one.

/** Deep freeze for plain data (objects and arrays). @template T @param {T} wert @returns {T} */
function friere(wert) {
  if (wert && typeof wert === "object" && !Object.isFrozen(wert)) {
    for (const k of Object.keys(wert)) friere(/** @type {any} */ (wert)[k]);
    Object.freeze(wert);
  }
  return wert;
}

/** @type {import("../leistungsbilder.js").HoaiTafel} */
export const TAFEL = friere({
  leistungsbild: "flaechennutzungsplan",
  paragraf: 20,
  fassung: "HOAI 2021",
  bezug: "flaeche_ha",
  einheit: "ha",
  zonen: ["I","II","III"],
  zeilen: [
  [1000, [70439, 85269, 100098, 114927]],
  [1250, [78957, 95579, 112202, 128824]],
  [1500, [86492, 104700, 122909, 141118]],
  [1750, [93260, 112894, 132527, 152161]],
  [2000, [99407, 120334, 141262, 162190]],
  [2500, [111311, 134745, 158178, 181612]],
  [3000, [121868, 147525, 173181, 198838]],
  [3500, [131387, 159047, 186707, 214367]],
  [4000, [140069, 169557, 199045, 228533]],
  [5000, [155461, 188190, 220918, 253647]],
  [6000, [168813, 204352, 239892, 275431]],
  [7000, [180589, 218607, 256626, 294645]],
  [8000, [191097, 231328, 271559, 311790]],
  [9000, [200556, 242779, 285001, 327224]],
  [10000, [209126, 253153, 297179, 341206]],
  [11000, [216893, 262555, 308217, 353878]],
  [12000, [223912, 271052, 318191, 365331]],
  [13000, [230331, 278822, 327313, 375804]],
  [14000, [236214, 285944, 335673, 385402]],
  [15000, [241614, 292480, 343346, 394213]],
  ],
  lph: [
  { nr: 1, bezeichnung: "Vorentwurf für die frühzeitigen Beteiligungen", prozent: 60 },
  { nr: 2, bezeichnung: "Entwurf zur öffentlichen Auslegung", prozent: 30 },
  { nr: 3, bezeichnung: "Plan zur Beschlussfassung", prozent: 10 },
  ],
  lphParagraf: 18,
  umbau_max_prozent: null,
  quelle: "https://www.gesetze-im-internet.de/hoai_2013/__20.html",
  abgerufen_am: "2026-09-28",
  status: "amtlich",
});
