// HOAI 2021 fee table § 29 and work-stage (LPH) percentages of § 24
// — gruenordnungsplan (decision E-13, plan 79-14).
//
// In:  nothing (import-free, like tafel2021.js). Out: TAFEL, a frozen HoaiTafel
//      record (typedef in ../leistungsbilder.js).
//
// Source: https://www.gesetze-im-internet.de/hoai_2013/__29.html (fetched 2026-09-28). Generated by
// .planning/phases/79-buchhaltung/tmp-e2e/hoai-tafeln-abruf.mjs — do not edit
// by hand; re-run the script on a new legal version and add a NEW file with a
// new `ab` date instead of overwriting this one.

/** Deep freeze for plain data (objects and arrays). @template T @param {T} wert @returns {T} */
function friere(wert) {
  if (wert && typeof wert === "object" && !Object.isFrozen(wert)) {
    for (const k of Object.keys(wert)) friere(/** @type {any} */ (wert)[k]);
    Object.freeze(wert);
  }
  return wert;
}

/** @type {import("../leistungsbilder.js").HoaiTafel} */
export const TAFEL = friere({
  leistungsbild: "gruenordnungsplan",
  paragraf: 29,
  fassung: "HOAI 2021",
  bezug: "flaeche_ha",
  einheit: "ha",
  zonen: ["I","II","III"],
  zeilen: [
  [1.5, [5219, 6067, 6980, 7828]],
  [2, [6008, 6985, 8036, 9013]],
  [3, [7450, 8661, 9965, 11175]],
  [4, [8770, 10195, 11730, 13155]],
  [5, [10006, 11632, 13383, 15009]],
  [10, [15445, 17955, 20658, 23167]],
  [15, [20183, 23462, 26994, 30274]],
  [20, [24513, 28496, 32785, 36769]],
  [25, [28560, 33201, 38199, 42840]],
  [30, [32394, 37658, 43326, 48590]],
  [40, [39580, 46011, 52938, 59370]],
  [50, [46282, 53803, 61902, 69423]],
  [75, [61579, 71586, 82362, 92369]],
  [100, [75430, 87687, 100887, 113145]],
  [125, [88255, 102597, 118042, 132383]],
  [150, [100288, 116585, 134136, 150433]],
  [175, [111675, 129822, 149366, 167513]],
  [200, [122516, 142425, 163866, 183774]],
  [225, [133555, 155258, 178630, 200333]],
  [250, [144284, 167730, 192980, 216426]],
  ],
  lph: [
  { nr: 1, bezeichnung: "Klären der Aufgabenstellung und Ermitteln des Leistungsumfangs", prozent: 3 },
  { nr: 2, bezeichnung: "Ermitteln der Planungsgrundlagen", prozent: 37 },
  { nr: 3, bezeichnung: "Vorläufige Fassung", prozent: 50 },
  { nr: 4, bezeichnung: "Abgestimmte Fassung", prozent: 10 },
  ],
  lphParagraf: 24,
  umbau_max_prozent: null,
  quelle: "https://www.gesetze-im-internet.de/hoai_2013/__29.html",
  abgerufen_am: "2026-09-28",
  status: "amtlich",
});
