// Registry-Stelle für 79-14 — je übertragener Tafel ein Import und ein Eintrag; sonst nichts ändern.
//
// Registry slot for the remaining HOAI 2021 fee tables (§§ 20, 21, 28–32, 44,
// 48, 52, 56, decision E-13). 79-01 creates it empty; 79-14 adds one import and
// one array entry per table file generated from the official text. Nothing else
// in this file changes, so the rate calculator (79-02) and the registry
// (../leistungsbilder.js) pick up new tables without a code change.
//
// In:  the generated data files (79-14: all eleven profiles of decision E-13
//      transferred — none failed the fetch script's checks). Out: WEITERE_TAFELN,
//      a frozen list of HoaiTafel records (typedef in ../leistungsbilder.js),
//      matched to the registry by their `leistungsbild` key.

import { TAFEL as BEBAUUNGSPLAN } from "./bebauungsplan.js";
import { TAFEL as FLAECHENNUTZUNGSPLAN } from "./flaechennutzungsplan.js";
import { TAFEL as GRUENORDNUNGSPLAN } from "./gruenordnungsplan.js";
import { TAFEL as INGENIEURBAUWERKE } from "./ingenieurbauwerke.js";
import { TAFEL as LANDSCHAFTSPFLEGERISCHER_BEGLEITPLAN } from "./landschaftspflegerischer_begleitplan.js";
import { TAFEL as LANDSCHAFTSPLAN } from "./landschaftsplan.js";
import { TAFEL as LANDSCHAFTSRAHMENPLAN } from "./landschaftsrahmenplan.js";
import { TAFEL as PFLEGE_ENTWICKLUNGSPLAN } from "./pflege_entwicklungsplan.js";
import { TAFEL as TECHNISCHE_AUSRUESTUNG } from "./technische_ausruestung.js";
import { TAFEL as TRAGWERKSPLANUNG } from "./tragwerksplanung.js";
import { TAFEL as VERKEHRSANLAGEN } from "./verkehrsanlagen.js";

/**
 * Additional HoaiTafel records beyond § 35/§ 40 (tafel2021.js) — the eleven
 * profiles of decision E-13, generated by
 * .planning/phases/79-buchhaltung/tmp-e2e/hoai-tafeln-abruf.mjs (79-14).
 * @type {ReadonlyArray<import("../leistungsbilder.js").HoaiTafel>}
 */
export const WEITERE_TAFELN = Object.freeze([
  FLAECHENNUTZUNGSPLAN,
  BEBAUUNGSPLAN,
  LANDSCHAFTSPLAN,
  GRUENORDNUNGSPLAN,
  LANDSCHAFTSRAHMENPLAN,
  LANDSCHAFTSPFLEGERISCHER_BEGLEITPLAN,
  PFLEGE_ENTWICKLUNGSPLAN,
  INGENIEURBAUWERKE,
  VERKEHRSANLAGEN,
  TRAGWERKSPLANUNG,
  TECHNISCHE_AUSRUESTUNG,
]);
