// HOAI 2021 fee table § 44 and work-stage (LPH) percentages of § 43
// — ingenieurbauwerke (decision E-13, plan 79-14).
//
// In:  nothing (import-free, like tafel2021.js). Out: TAFEL, a frozen HoaiTafel
//      record (typedef in ../leistungsbilder.js).
//
// Source: https://www.gesetze-im-internet.de/hoai_2013/__44.html (fetched 2026-09-28). Generated by
// .planning/phases/79-buchhaltung/tmp-e2e/hoai-tafeln-abruf.mjs — do not edit
// by hand; re-run the script on a new legal version and add a NEW file with a
// new `ab` date instead of overwriting this one.

/** Deep freeze for plain data (objects and arrays). @template T @param {T} wert @returns {T} */
function friere(wert) {
  if (wert && typeof wert === "object" && !Object.isFrozen(wert)) {
    for (const k of Object.keys(wert)) friere(/** @type {any} */ (wert)[k]);
    Object.freeze(wert);
  }
  return wert;
}

/** @type {import("../leistungsbilder.js").HoaiTafel} */
export const TAFEL = friere({
  leistungsbild: "ingenieurbauwerke",
  paragraf: 44,
  fassung: "HOAI 2021",
  bezug: "anrechenbare_kosten_euro",
  einheit: "EUR",
  zonen: ["I","II","III","IV","V"],
  zeilen: [
  [25000, [3449, 4109, 4768, 5428, 6036, 6696]],
  [35000, [4475, 5331, 6186, 7042, 7831, 8687]],
  [50000, [5897, 7024, 8152, 9279, 10320, 11447]],
  [75000, [8069, 9611, 11154, 12697, 14121, 15663]],
  [100000, [10079, 12005, 13932, 15859, 17637, 19564]],
  [150000, [13786, 16422, 19058, 21693, 24126, 26762]],
  [200000, [17215, 20506, 23797, 27088, 30126, 33417]],
  [300000, [23534, 28033, 32532, 37031, 41185, 45684]],
  [500000, [34865, 41530, 48195, 54861, 61013, 67679]],
  [750000, [47576, 56672, 65767, 74863, 83258, 92354]],
  [1000000, [59264, 70594, 81924, 93254, 103712, 115042]],
  [1500000, [80998, 96482, 111967, 127452, 141746, 157230]],
  [2000000, [101054, 120373, 139692, 159011, 176844, 196163]],
  [3000000, [137907, 164272, 190636, 217001, 241338, 267702]],
  [5000000, [203584, 242504, 281425, 320345, 356272, 395192]],
  [7500000, [278415, 331642, 384868, 438095, 487227, 540453]],
  [10000000, [347568, 414014, 480461, 546908, 608244, 674690]],
  [15000000, [474901, 565691, 656480, 747270, 831076, 921866]],
  [20000000, [592324, 705563, 818801, 932040, 1036568, 1149806]],
  [25000000, [702770, 837123, 971476, 1105829, 1229848, 1364201]],
  ],
  lph: [
  { nr: 1, bezeichnung: "Grundlagenermittlung", prozent: 2 },
  { nr: 2, bezeichnung: "Vorplanung", prozent: 20 },
  { nr: 3, bezeichnung: "Entwurfsplanung", prozent: 25 },
  { nr: 4, bezeichnung: "Genehmigungsplanung", prozent: 5 },
  { nr: 5, bezeichnung: "Ausführungsplanung", prozent: 15 },
  { nr: 6, bezeichnung: "Vorbereitung der Vergabe", prozent: 13 },
  { nr: 7, bezeichnung: "Mitwirkung bei der Vergabe", prozent: 4 },
  { nr: 8, bezeichnung: "Bauoberleitung", prozent: 15 },
  { nr: 9, bezeichnung: "Objektbetreuung", prozent: 1 },
  ],
  lphParagraf: 43,
  umbau_max_prozent: 33,
  quelle: "https://www.gesetze-im-internet.de/hoai_2013/__44.html",
  abgerufen_am: "2026-09-28",
  status: "amtlich",
});
