// HOAI 2021 fee table § 31 and work-stage (LPH) percentages of § 26
// — landschaftspflegerischer_begleitplan (decision E-13, plan 79-14).
//
// In:  nothing (import-free, like tafel2021.js). Out: TAFEL, a frozen HoaiTafel
//      record (typedef in ../leistungsbilder.js).
//
// Source: https://www.gesetze-im-internet.de/hoai_2013/__31.html (fetched 2026-09-28). Generated by
// .planning/phases/79-buchhaltung/tmp-e2e/hoai-tafeln-abruf.mjs — do not edit
// by hand; re-run the script on a new legal version and add a NEW file with a
// new `ab` date instead of overwriting this one.

/** Deep freeze for plain data (objects and arrays). @template T @param {T} wert @returns {T} */
function friere(wert) {
  if (wert && typeof wert === "object" && !Object.isFrozen(wert)) {
    for (const k of Object.keys(wert)) friere(/** @type {any} */ (wert)[k]);
    Object.freeze(wert);
  }
  return wert;
}

/** @type {import("../leistungsbilder.js").HoaiTafel} */
export const TAFEL = friere({
  leistungsbild: "landschaftspflegerischer_begleitplan",
  paragraf: 31,
  fassung: "HOAI 2021",
  bezug: "flaeche_ha",
  einheit: "ha",
  zonen: ["I","II","III"],
  zeilen: [
  [6, [5324, 6189, 7121, 7986]],
  [8, [6130, 7126, 8199, 9195]],
  [12, [7600, 8836, 10166, 11401]],
  [16, [8947, 10401, 11966, 13420]],
  [20, [10207, 11866, 13652, 15311]],
  [40, [15755, 18315, 21072, 23632]],
  [100, [29126, 33859, 38956, 43689]],
  [200, [47180, 54846, 63103, 70769]],
  [300, [62748, 72944, 83925, 94121]],
  [400, [76829, 89314, 102759, 115244]],
  [500, [89855, 104456, 120181, 134782]],
  [600, [102062, 118647, 136508, 153093]],
  [700, [113602, 132062, 151942, 170402]],
  [800, [124575, 144819, 166620, 186863]],
  [1200, [167729, 194985, 224338, 251594]],
  [1600, [207279, 240961, 277235, 310918]],
  [2000, [244349, 284056, 326817, 366524]],
  [2400, [279559, 324987, 373910, 419338]],
  [3200, [343814, 399683, 459851, 515720]],
  [4000, [400847, 465985, 536133, 601270]],
  ],
  lph: [
  { nr: 1, bezeichnung: "Klären der Aufgabenstellung und Ermitteln des Leistungsumfangs", prozent: 3 },
  { nr: 2, bezeichnung: "Ermitteln und Bewerten der Planungsgrundlagen", prozent: 37 },
  { nr: 3, bezeichnung: "Vorläufige Fassung", prozent: 50 },
  { nr: 4, bezeichnung: "Abgestimmte Fassung", prozent: 10 },
  ],
  lphParagraf: 26,
  umbau_max_prozent: null,
  quelle: "https://www.gesetze-im-internet.de/hoai_2013/__31.html",
  abgerufen_am: "2026-09-28",
  status: "amtlich",
});
