// HOAI 2021 fee table § 30 and work-stage (LPH) percentages of § 25
// — landschaftsrahmenplan (decision E-13, plan 79-14).
//
// In:  nothing (import-free, like tafel2021.js). Out: TAFEL, a frozen HoaiTafel
//      record (typedef in ../leistungsbilder.js).
//
// Source: https://www.gesetze-im-internet.de/hoai_2013/__30.html (fetched 2026-09-28). Generated by
// .planning/phases/79-buchhaltung/tmp-e2e/hoai-tafeln-abruf.mjs — do not edit
// by hand; re-run the script on a new legal version and add a NEW file with a
// new `ab` date instead of overwriting this one.

/** Deep freeze for plain data (objects and arrays). @template T @param {T} wert @returns {T} */
function friere(wert) {
  if (wert && typeof wert === "object" && !Object.isFrozen(wert)) {
    for (const k of Object.keys(wert)) friere(/** @type {any} */ (wert)[k]);
    Object.freeze(wert);
  }
  return wert;
}

/** @type {import("../leistungsbilder.js").HoaiTafel} */
export const TAFEL = friere({
  leistungsbild: "landschaftsrahmenplan",
  paragraf: 30,
  fassung: "HOAI 2021",
  bezug: "flaeche_ha",
  einheit: "ha",
  zonen: ["I","II","III"],
  zeilen: [
  [5000, [61880, 71935, 82764, 92820]],
  [6000, [67933, 78973, 90861, 101900]],
  [7000, [73473, 85413, 98270, 110210]],
  [8000, [78600, 91373, 105128, 117901]],
  [9000, [83385, 96936, 111528, 125078]],
  [10000, [87880, 102161, 117540, 131820]],
  [12000, [96149, 111773, 128599, 144223]],
  [14000, [103631, 120471, 138607, 155447]],
  [16000, [110477, 128430, 147763, 165716]],
  [18000, [116791, 135769, 156208, 175186]],
  [20000, [122649, 142580, 164043, 183974]],
  [25000, [138047, 160480, 184638, 207070]],
  [30000, [152052, 176761, 203370, 228078]],
  [40000, [177097, 205875, 236867, 265645]],
  [50000, [199330, 231721, 266604, 298995]],
  [60000, [219553, 255230, 293652, 329329]],
  [70000, [238243, 276958, 318650, 357365]],
  [80000, [253946, 295212, 339652, 380918]],
  [90000, [268420, 312038, 359011, 402630]],
  [100000, [281843, 327643, 376965, 422765]],
  ],
  lph: [
  { nr: 1, bezeichnung: "Klären der Aufgabenstellung und Ermitteln des Leistungsumfangs", prozent: 3 },
  { nr: 2, bezeichnung: "Ermitteln der Planungsgrundlagen", prozent: 37 },
  { nr: 3, bezeichnung: "Vorläufige Fassung", prozent: 50 },
  { nr: 4, bezeichnung: "Abgestimmte Fassung", prozent: 10 },
  ],
  lphParagraf: 25,
  umbau_max_prozent: null,
  quelle: "https://www.gesetze-im-internet.de/hoai_2013/__30.html",
  abgerufen_am: "2026-09-28",
  status: "amtlich",
});
