// HOAI 2021 fee table § 28 and work-stage (LPH) percentages of § 23
// — landschaftsplan (decision E-13, plan 79-14).
//
// In:  nothing (import-free, like tafel2021.js). Out: TAFEL, a frozen HoaiTafel
//      record (typedef in ../leistungsbilder.js).
//
// Source: https://www.gesetze-im-internet.de/hoai_2013/__28.html (fetched 2026-09-28). Generated by
// .planning/phases/79-buchhaltung/tmp-e2e/hoai-tafeln-abruf.mjs — do not edit
// by hand; re-run the script on a new legal version and add a NEW file with a
// new `ab` date instead of overwriting this one.

/** Deep freeze for plain data (objects and arrays). @template T @param {T} wert @returns {T} */
function friere(wert) {
  if (wert && typeof wert === "object" && !Object.isFrozen(wert)) {
    for (const k of Object.keys(wert)) friere(/** @type {any} */ (wert)[k]);
    Object.freeze(wert);
  }
  return wert;
}

/** @type {import("../leistungsbilder.js").HoaiTafel} */
export const TAFEL = friere({
  leistungsbild: "landschaftsplan",
  paragraf: 28,
  fassung: "HOAI 2021",
  bezug: "flaeche_ha",
  einheit: "ha",
  zonen: ["I","II","III"],
  zeilen: [
  [1000, [23403, 27963, 32826, 37385]],
  [1250, [26560, 31735, 37254, 42428]],
  [1500, [29445, 35182, 41300, 47036]],
  [1750, [32119, 38375, 45049, 51306]],
  [2000, [34620, 41364, 48558, 55302]],
  [2500, [39212, 46851, 54999, 62638]],
  [3000, [43374, 51824, 60837, 69286]],
  [3500, [47199, 56393, 66201, 75396]],
  [4000, [50747, 60633, 71178, 81064]],
  [5000, [57180, 68319, 80200, 91339]],
  [6000, [63562, 75944, 89151, 101533]],
  [7000, [69505, 83045, 97487, 111027]],
  [8000, [75095, 89724, 105329, 119958]],
  [9000, [80394, 96055, 112761, 128422]],
  [10000, [85445, 102090, 119845, 136490]],
  [11000, [89986, 107516, 126214, 143744]],
  [12000, [94309, 112681, 132278, 150650]],
  [13000, [98438, 117615, 138069, 157246]],
  [14000, [102392, 122339, 143615, 163562]],
  [15000, [106187, 126873, 148938, 169623]],
  ],
  lph: [
  { nr: 1, bezeichnung: "Klären der Aufgabenstellung und Ermitteln des Leistungsumfangs", prozent: 3 },
  { nr: 2, bezeichnung: "Ermitteln der Planungsgrundlagen", prozent: 37 },
  { nr: 3, bezeichnung: "Vorläufige Fassung", prozent: 50 },
  { nr: 4, bezeichnung: "Abgestimmte Fassung", prozent: 10 },
  ],
  lphParagraf: 23,
  umbau_max_prozent: null,
  quelle: "https://www.gesetze-im-internet.de/hoai_2013/__28.html",
  abgerufen_am: "2026-09-28",
  status: "amtlich",
});
