// HOAI 2021 fee table § 32 and work-stage (LPH) percentages of § 27
// — pflege_entwicklungsplan (decision E-13, plan 79-14).
//
// In:  nothing (import-free, like tafel2021.js). Out: TAFEL, a frozen HoaiTafel
//      record (typedef in ../leistungsbilder.js).
//
// Source: https://www.gesetze-im-internet.de/hoai_2013/__32.html (fetched 2026-09-28). Generated by
// .planning/phases/79-buchhaltung/tmp-e2e/hoai-tafeln-abruf.mjs — do not edit
// by hand; re-run the script on a new legal version and add a NEW file with a
// new `ab` date instead of overwriting this one.

/** Deep freeze for plain data (objects and arrays). @template T @param {T} wert @returns {T} */
function friere(wert) {
  if (wert && typeof wert === "object" && !Object.isFrozen(wert)) {
    for (const k of Object.keys(wert)) friere(/** @type {any} */ (wert)[k]);
    Object.freeze(wert);
  }
  return wert;
}

/** @type {import("../leistungsbilder.js").HoaiTafel} */
export const TAFEL = friere({
  leistungsbild: "pflege_entwicklungsplan",
  paragraf: 32,
  fassung: "HOAI 2021",
  bezug: "flaeche_ha",
  einheit: "ha",
  zonen: ["I","II","III"],
  zeilen: [
  [5, [3852, 7704, 11556, 15408]],
  [10, [4802, 9603, 14405, 19207]],
  [15, [5481, 10963, 16444, 21925]],
  [20, [6029, 12058, 18087, 24116]],
  [30, [6906, 13813, 20719, 27626]],
  [40, [7612, 15225, 22837, 30450]],
  [50, [8213, 16425, 24638, 32851]],
  [75, [9433, 18866, 28298, 37731]],
  [100, [10408, 20816, 31224, 41633]],
  [150, [11949, 23899, 35848, 47798]],
  [200, [13165, 26330, 39495, 52660]],
  [300, [15318, 30636, 45954, 61272]],
  [400, [17087, 34174, 51262, 68349]],
  [500, [18621, 37242, 55863, 74484]],
  [750, [21833, 43666, 65500, 87333]],
  [1000, [24507, 49014, 73522, 98029]],
  [1500, [28966, 57932, 86898, 115864]],
  [2500, [36065, 72131, 108196, 144261]],
  [5000, [49288, 98575, 147863, 197150]],
  [10000, [69015, 138029, 207044, 276058]],
  ],
  lph: [
  { nr: 1, bezeichnung: "Zusammenstellen der Ausgangsbedingungen", prozent: 3 },
  { nr: 2, bezeichnung: "Ermitteln der Planungsgrundlagen", prozent: 37 },
  { nr: 3, bezeichnung: "Vorläufige Fassung", prozent: 50 },
  { nr: 4, bezeichnung: "Abgestimmte Fassung", prozent: 10 },
  ],
  lphParagraf: 27,
  umbau_max_prozent: null,
  quelle: "https://www.gesetze-im-internet.de/hoai_2013/__32.html",
  abgerufen_am: "2026-09-28",
  status: "amtlich",
});
