// HOAI 2021 fee table § 56 and work-stage (LPH) percentages of § 55
// — technische_ausruestung (decision E-13, plan 79-14).
//
// In:  nothing (import-free, like tafel2021.js). Out: TAFEL, a frozen HoaiTafel
//      record (typedef in ../leistungsbilder.js).
//
// Source: https://www.gesetze-im-internet.de/hoai_2013/__56.html (fetched 2026-09-28). Generated by
// .planning/phases/79-buchhaltung/tmp-e2e/hoai-tafeln-abruf.mjs — do not edit
// by hand; re-run the script on a new legal version and add a NEW file with a
// new `ab` date instead of overwriting this one.

/** Deep freeze for plain data (objects and arrays). @template T @param {T} wert @returns {T} */
function friere(wert) {
  if (wert && typeof wert === "object" && !Object.isFrozen(wert)) {
    for (const k of Object.keys(wert)) friere(/** @type {any} */ (wert)[k]);
    Object.freeze(wert);
  }
  return wert;
}

/** @type {import("../leistungsbilder.js").HoaiTafel} */
export const TAFEL = friere({
  leistungsbild: "technische_ausruestung",
  paragraf: 56,
  fassung: "HOAI 2021",
  bezug: "anrechenbare_kosten_euro",
  einheit: "EUR",
  zonen: ["I","II","III"],
  zeilen: [
  [5000, [2132, 2547, 2990, 3405]],
  [10000, [3689, 4408, 5174, 5893]],
  [15000, [5084, 6075, 7131, 8122]],
  [25000, [7615, 9098, 10681, 12164]],
  [35000, [9934, 11869, 13934, 15869]],
  [50000, [13165, 15729, 18465, 21029]],
  [75000, [18122, 21652, 25418, 28948]],
  [100000, [22723, 27150, 31872, 36299]],
  [150000, [31228, 37311, 43800, 49883]],
  [250000, [46640, 55726, 65418, 74504]],
  [500000, [80684, 96402, 113168, 128886]],
  [750000, [111105, 132749, 155836, 177480]],
  [1000000, [139347, 166493, 195448, 222594]],
  [1250000, [166043, 198389, 232891, 265237]],
  [1500000, [191545, 228859, 268660, 305974]],
  [2000000, [239792, 286504, 336331, 383044]],
  [2500000, [285649, 341295, 400650, 456296]],
  [3000000, [329420, 393593, 462044, 526217]],
  [3500000, [371491, 443859, 521052, 593420]],
  [4000000, [412126, 492410, 578046, 658331]],
  ],
  lph: [
  { nr: 1, bezeichnung: "Grundlagenermittlung", prozent: 2 },
  { nr: 2, bezeichnung: "Vorplanung", prozent: 9 },
  { nr: 3, bezeichnung: "Entwurfsplanung", prozent: 17 },
  { nr: 4, bezeichnung: "Genehmigungsplanung", prozent: 2 },
  { nr: 5, bezeichnung: "Ausführungsplanung", prozent: 22 },
  { nr: 6, bezeichnung: "Vorbereitung der Vergabe", prozent: 7 },
  { nr: 7, bezeichnung: "Mitwirkung bei der Vergabe", prozent: 5 },
  { nr: 8, bezeichnung: "Objektüberwachung – Bauüberwachung", prozent: 35 },
  { nr: 9, bezeichnung: "Objektbetreuung", prozent: 1 },
  ],
  lphParagraf: 55,
  umbau_max_prozent: 50,
  quelle: "https://www.gesetze-im-internet.de/hoai_2013/__56.html",
  abgerufen_am: "2026-09-28",
  status: "amtlich",
});
