// HOAI 2021 fee table § 52 and work-stage (LPH) percentages of § 51
// — tragwerksplanung (decision E-13, plan 79-14).
//
// In:  nothing (import-free, like tafel2021.js). Out: TAFEL, a frozen HoaiTafel
//      record (typedef in ../leistungsbilder.js).
//
// Source: https://www.gesetze-im-internet.de/hoai_2013/__52.html (fetched 2026-09-28). Generated by
// .planning/phases/79-buchhaltung/tmp-e2e/hoai-tafeln-abruf.mjs — do not edit
// by hand; re-run the script on a new legal version and add a NEW file with a
// new `ab` date instead of overwriting this one.

/** Deep freeze for plain data (objects and arrays). @template T @param {T} wert @returns {T} */
function friere(wert) {
  if (wert && typeof wert === "object" && !Object.isFrozen(wert)) {
    for (const k of Object.keys(wert)) friere(/** @type {any} */ (wert)[k]);
    Object.freeze(wert);
  }
  return wert;
}

/** @type {import("../leistungsbilder.js").HoaiTafel} */
export const TAFEL = friere({
  leistungsbild: "tragwerksplanung",
  paragraf: 52,
  fassung: "HOAI 2021",
  bezug: "anrechenbare_kosten_euro",
  einheit: "EUR",
  zonen: ["I","II","III","IV","V"],
  zeilen: [
  [10000, [1461, 1624, 2064, 2575, 3015, 3178]],
  [15000, [2011, 2234, 2841, 3543, 4149, 4373]],
  [25000, [3006, 3340, 4247, 5296, 6203, 6537]],
  [50000, [5187, 5763, 7327, 9139, 10703, 11279]],
  [75000, [7135, 7928, 10080, 12572, 14724, 15517]],
  [100000, [8946, 9940, 12639, 15763, 18461, 19455]],
  [150000, [12303, 13670, 17380, 21677, 25387, 26754]],
  [250000, [18370, 20411, 25951, 32365, 37906, 39947]],
  [350000, [23909, 26565, 33776, 42125, 49335, 51992]],
  [500000, [31594, 35105, 44633, 55666, 65194, 68705]],
  [750000, [43463, 48293, 61401, 76578, 89686, 94515]],
  [1000000, [54495, 60550, 76984, 96014, 112449, 118504]],
  [1250000, [64940, 72155, 91740, 114418, 134003, 141218]],
  [1500000, [74938, 83265, 105865, 132034, 154635, 162961]],
  [2000000, [93923, 104358, 132684, 165483, 193808, 204244]],
  [3000000, [129059, 143398, 182321, 227389, 266311, 280651]],
  [5000000, [192384, 213760, 271781, 338962, 396983, 418359]],
  [7500000, [264487, 293874, 373640, 466001, 545767, 575154]],
  [10000000, [331398, 368220, 468166, 583892, 683838, 720660]],
  [15000000, [455117, 505686, 642943, 801873, 939131, 989699]],
  ],
  lph: [
  { nr: 1, bezeichnung: "Grundlagenermittlung", prozent: 3 },
  { nr: 2, bezeichnung: "Vorplanung", prozent: 10 },
  { nr: 3, bezeichnung: "Entwurfsplanung", prozent: 15 },
  { nr: 4, bezeichnung: "Genehmigungsplanung", prozent: 30 },
  { nr: 5, bezeichnung: "Ausführungsplanung", prozent: 40 },
  { nr: 6, bezeichnung: "Vorbereitung der Vergabe", prozent: 2 },
  ],
  lphParagraf: 51,
  umbau_max_prozent: 50,
  quelle: "https://www.gesetze-im-internet.de/hoai_2013/__52.html",
  abgerufen_am: "2026-09-28",
  status: "amtlich",
});
