// HOAI 2021 fee table § 48 and work-stage (LPH) percentages of § 47
// — verkehrsanlagen (decision E-13, plan 79-14).
//
// In:  nothing (import-free, like tafel2021.js). Out: TAFEL, a frozen HoaiTafel
//      record (typedef in ../leistungsbilder.js).
//
// Source: https://www.gesetze-im-internet.de/hoai_2013/__48.html (fetched 2026-09-28). Generated by
// .planning/phases/79-buchhaltung/tmp-e2e/hoai-tafeln-abruf.mjs — do not edit
// by hand; re-run the script on a new legal version and add a NEW file with a
// new `ab` date instead of overwriting this one.

/** Deep freeze for plain data (objects and arrays). @template T @param {T} wert @returns {T} */
function friere(wert) {
  if (wert && typeof wert === "object" && !Object.isFrozen(wert)) {
    for (const k of Object.keys(wert)) friere(/** @type {any} */ (wert)[k]);
    Object.freeze(wert);
  }
  return wert;
}

/** @type {import("../leistungsbilder.js").HoaiTafel} */
export const TAFEL = friere({
  leistungsbild: "verkehrsanlagen",
  paragraf: 48,
  fassung: "HOAI 2021",
  bezug: "anrechenbare_kosten_euro",
  einheit: "EUR",
  zonen: ["I","II","III","IV","V"],
  zeilen: [
  [25000, [3882, 4624, 5366, 6108, 6793, 7535]],
  [35000, [4981, 5933, 6885, 7837, 8716, 9668]],
  [50000, [6487, 7727, 8967, 10207, 11352, 12592]],
  [75000, [8759, 10434, 12108, 13783, 15328, 17003]],
  [100000, [10839, 12911, 14983, 17056, 18968, 21041]],
  [150000, [14634, 17432, 20229, 23027, 25610, 28407]],
  [200000, [18106, 21567, 25029, 28490, 31685, 35147]],
  [300000, [24435, 29106, 33778, 38449, 42761, 47433]],
  [500000, [35622, 42433, 49243, 56053, 62339, 69149]],
  [750000, [48001, 57178, 66355, 75532, 84002, 93179]],
  [1000000, [59267, 70597, 81928, 93258, 103717, 115047]],
  [1500000, [80009, 95305, 110600, 125896, 140015, 155311]],
  [2000000, [98962, 117881, 136800, 155719, 173183, 192102]],
  [3000000, [133441, 158951, 184462, 209973, 233521, 259032]],
  [5000000, [194094, 231200, 268306, 305412, 339664, 376770]],
  [7500000, [262407, 312573, 362739, 412905, 459212, 509378]],
  [10000000, [324978, 387107, 449235, 511363, 568712, 630840]],
  [15000000, [439179, 523140, 607101, 691062, 768564, 852525]],
  [20000000, [543619, 647546, 751473, 855401, 951333, 1055260]],
  [25000000, [641265, 763860, 886454, 1009049, 1122213, 1244808]],
  ],
  lph: [
  { nr: 1, bezeichnung: "Grundlagenermittlung", prozent: 2 },
  { nr: 2, bezeichnung: "Vorplanung", prozent: 20 },
  { nr: 3, bezeichnung: "Entwurfsplanung", prozent: 25 },
  { nr: 4, bezeichnung: "Genehmigungsplanung", prozent: 8 },
  { nr: 5, bezeichnung: "Ausführungsplanung", prozent: 15 },
  { nr: 6, bezeichnung: "Vorbereitung der Vergabe", prozent: 10 },
  { nr: 7, bezeichnung: "Mitwirkung bei der Vergabe", prozent: 4 },
  { nr: 8, bezeichnung: "Bauoberleitung", prozent: 15 },
  { nr: 9, bezeichnung: "Objektbetreuung", prozent: 1 },
  ],
  lphParagraf: 47,
  umbau_max_prozent: 33,
  quelle: "https://www.gesetze-im-internet.de/hoai_2013/__48.html",
  abgerufen_am: "2026-09-28",
  status: "amtlich",
});
